baseURL = "https://jHoon99.github.io/"
languageCode = "ko-kr"
title = "jHoon"
theme = "hugo-theme-stack"
defaultContentLanguage = "ko"
hasCJKLanguage = true
timeZone = "Asia/Seoul"
enableRobotsTXT = true

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
