baseURL = 'https://jHoon99.github.io/'
languageCode = 'ko-kr'
title = "jHoon's Flutter Study"
theme = "kong-htop"
paginate = 10
pluralizelisttitles = false

[params]
    author = "jHoon"
    title = "jHoon's Flutter Study"
    brand = "jHoon"
    description = "iOS 개발자의 Flutter 공부 기록"
    dark_mode = true
    mainSections = ["posts"]

    menu = [
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
        {Name = "Categories", URL = "/categories/", HasChildren = false},
        {Name = "Tags", URL = "/tags/", HasChildren = false},
    ]

    rss_icon = true
    rss_section = "posts"

    # Sidebar colors
    sidebar_bg_color = "#202020"
    sidebar_img_border_color = "#515151"
    sidebar_p_color = "#909090"
    sidebar_h1_color = "#FFF"
    sidebar_a_color = "#FFF"
    sidebar_socials_color = "#FFF"
    moon_sun_color = "#FFF"
    moon_sun_background_color = "#515151"

    # Light mode
    text_color = "#222"
    content_bg_color = "#FAF9F6"
    post_title_color = "#303030"
    list_color = "#5a5a5a"
    link_color = "#268bd2"
    date_color = "#515151"
    table_border_color = "#E5E5E5"
    table_stripe_color = "#F9F9F9"

    # Dark mode
    text_color_dark = "#eee"
    content_bg_color_dark = "#121212"
    post_title_color_dark = "#DBE2E9"
    list_color_dark = "#9d9d9d"
    link_color_dark = "#268bd2"
    date_color_dark = "#9a9a9a"
    table_border_color_dark = "#515151"
    table_stripe_color_dark = "#202020"

[params.meta]
    favicon = true

[taxonomies]
    series = 'series'
    tags = 'tags'
    categories = 'categories'

[outputs]
    home = ["HTML", "RSS", "JSON"]
    section = ["HTML"]
    page = ["HTML"]

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
